version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fortnitedash-server
    env_file:
      - ./server/.env
    ports:
      - '4201:3001'
    networks:
      - fortnitedash-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: fortnitedash-client
    depends_on:
      - server
    ports:
      - '4200:80'
    networks:
      - fortnitedash-network

networks:
  fortnitedash-network:
    driver: bridge